/** @type {import('tailwindcss').Config} */
export default {
	content: [
		"./Resources/Private/Fusion/**/*.fusion",
		"./Resources/Private/Templates/**/*.html",
		"./Resources/Private/JavaScript/**/*.{js,vue}",
		"./Resources/Private/Styles/**/*.css"
	],
	theme: {
		extend: {
			colors: {
				// Apfelblüte Brand Colors
				'apfel-dark-grey': '#3C3C3B',
				'apfel-olive': '#AAB082',
				'apfel-olive-light': '#C4C6B3',
				'apfel-olive-dark': '#8a9068',
				'apfel-rose': '#E9CED4',
				'apfel-rose-light': '#faf4f6',
				'apfel-rose-dark': '#e8d4da',
				'apfel-green': '#3D4A24',
				'apfel-green-light': '#5a6d38',
				'apfel-green-dark': '#2a331a',
				'apfel-text': '#3D4A24',
				'apfel-text-light': '#5a6d38',
				'apfel-white': '#FFFFFF',
				'apfel-bg-light': '#F5E9EC',
				'apfel-footer': '#AAB082',
				// Apfelblüte Primary Color Palette (Olive Green)
				primary: {
					50: '#f7f8f3',
					100: '#eef0e6',
					200: '#dde1cd',
					300: '#c4c9a8',
					400: '#AAB082',
					500: '#AAB082',
					600: '#8a9068',
					700: '#6b7050',
					800: '#565a41',
					900: '#474a37',
				},
				// Apfelblüte Secondary Color Palette (Rose/Pink)
				secondary: {
					50: '#fdfbfc',
					100: '#faf4f6',
					200: '#F5E9EC',
					300: '#e8d4da',
					400: '#d4b8c2',
					500: '#F5E9EC',
					600: '#c9a3b0',
					700: '#a8818f',
					800: '#8a6774',
					900: '#725761',
				},
				// Apfelblüte Accent Color Palette (Dark Green)
				accent: {
					50: '#f4f5f1',
					100: '#e5e8dc',
					200: '#c9d0b6',
					300: '#a6b188',
					400: '#7a8a56',
					500: '#3D4A24',
					600: '#353f20',
					700: '#2a331a',
					800: '#222914',
					900: '#1a1f10',
				},
			},
			fontFamily: {
				'headline': ['"Amatic SC"', 'Georgia', 'serif'],
				'script': ['"Amatic SC"', 'cursive', 'sans-serif'],
				'body': ['Inter', 'system-ui', 'sans-serif'],
				'light': ['Inter', 'system-ui', 'sans-serif'],
				'light-body': ['Inter', 'system-ui', 'sans-serif'],
				'sans': ['Inter', 'system-ui', 'sans-serif'],
				'serif': ['"Amatic SC"', 'Georgia', 'serif'],
				'mono': ['ui-monospace', 'SFMono-Regular'],
			},
			fontSize: {
				'xs': '.75rem',
				'sm': '.875rem',
				'base': '1rem',
				'lg': '1.125rem',
				'xl': '1.25rem',
				'2xl': '1.5rem',
				'3xl': '1.875rem',
				'4xl': '2.25rem',
				'5xl': '3rem',
				'6xl': '3.75rem',
				'7xl': '4.5rem',
			},
			spacing: {
				'18': '4.5rem',
				'88': '22rem',
				'128': '32rem',
			},
			borderRadius: {
				'sm': '0.125rem',
				'DEFAULT': '0.25rem',
				'md': '0.375rem',
				'lg': '0.5rem',
				'xl': '0.75rem',
				'2xl': '1rem',
				'3xl': '1.5rem',
			},
			container: {
				center: true,
				padding: {
					DEFAULT: '1rem',
					sm: '2rem',
					lg: '4rem',
					xl: '5rem',
					'2xl': '6rem',
				},
			},
			typography: (theme) => ({
				DEFAULT: {
					css: {
						color: theme('colors.apfel-text'),
						fontWeight: '400',
						strong: {
							color: theme('colors.apfel-green'),
							fontWeight: '700',
						},
						em: {
							fontStyle: 'italic',
						},
						a: {
							color: theme('colors.apfel-green'),
							textDecoration: 'underline',
							'&:hover': {
								color: theme('colors.apfel-green-dark'),
							},
						},
						h1: {
							color: theme('colors.apfel-green'),
							fontFamily: theme('fontFamily.headline'),
							fontWeight: '400',
							fontSize: '4.375rem',
							marginTop: '0',
							marginBottom: '1.5rem',
							textTransform: 'uppercase',
							letterSpacing: '0.035em',
						},
						h2: {
							color: theme('colors.apfel-green'),
							fontFamily: theme('fontFamily.headline'),
							fontWeight: '400',
							fontSize: '3.125rem',
							marginTop: '2rem',
							marginBottom: '1rem',
							textTransform: 'uppercase',
							letterSpacing: '0.035em',
						},
						h3: {
							color: theme('colors.apfel-green'),
							fontFamily: theme('fontFamily.script'),
							fontWeight: '700',
							fontSize: '2.9375rem',
							marginTop: '1.5rem',
							marginBottom: '0.75rem',
							textTransform: 'uppercase',
							letterSpacing: '0.06em',
						},
						h4: {
							color: theme('colors.apfel-green'),
							fontFamily: theme('fontFamily.headline'),
							fontWeight: '400',
							fontSize: '1.5rem',
							marginTop: '1rem',
							marginBottom: '0.5rem',
						},
						p: {
							marginBottom: '1rem',
							lineHeight: '1.75',
						},
						ul: {
							listStyleType: 'disc',
							paddingLeft: '1.5rem',
							marginBottom: '1rem',
							'li': {
								marginBottom: '0.5rem',
								paddingLeft: '0.25rem',
							},
						},
						ol: {
							listStyleType: 'decimal',
							paddingLeft: '1.5rem',
							marginBottom: '1rem',
							'li': {
								marginBottom: '0.5rem',
								paddingLeft: '0.25rem',
							},
						},
						'ul ul, ol ol': {
							marginTop: '0.5rem',
							marginBottom: '0.5rem',
						},
					},
				},
				lg: {
					css: {
						fontSize: '1.125rem',
						lineHeight: '1.75',
						p: {
							marginBottom: '1.25rem',
						},
					},
				},
			}),
		},
	},
	plugins: [
		require('@tailwindcss/typography'),
		require('@tailwindcss/aspect-ratio'),
	],
}
