-
  name: 'Thorwarth.BaseSite Search API'
  uriPattern: 'api/search'
  defaults:
    '@package': 'Thorwarth.BaseSite'
    '@controller': 'Search'
    '@action': 'search'
    '@format': 'json'
  httpMethods: ['GET']