/** @type {import('tailwindcss').Config} */
export default {
	content: [
		"./Resources/Private/Fusion/**/*.fusion",
		"./Resources/Private/Templates/**/*.html",
		"./Resources/Private/JavaScript/**/*.{js,vue}",
		"./Resources/Private/Styles/**/*.css"
	],
	theme: {
		extend: {
			colors: {
				'caspary-blue': '#2c5c6a',
				'caspary-blue-text': '#528495',
				'caspary-blue-light': '#A9CFCF',
				'caspary-gray': '#2B2B2A',
				'caspary-gray-medium': '#B4B1B8',
				'caspary-light-gray': '#7B7B7B',
				'caspary-text': '#4A4A49',
				'caspary-purple': '#7B5664',
				'caspary-purple-dark': '#9D939D',
				'caspary-footer': '#5d4d5e',
				'caspary-blue-alt': '#6fa1ae',
				'caspary-team-member-bg': '#f4f1ed',
				'caspary-team-member-text': '#818384',
				// Legacy colors for backward compatibility
				primary: {
					50: '#faf9f9',
					100: '#f5f3f3',
					200: '#ebe7e7',
					300: '#dfd8d8',
					400: '#cfc5c5',
					500: '#b8abab',
					600: '#9e8f8f',
					700: '#847676',
					800: '#6b5f5f',
					900: '#574e4e',
				},
				secondary: {
					50: '#e8f5f4',
					100: '#d1ebe9',
					200: '#a3d7d3',
					300: '#75c3bd',
					400: '#47afa7',
					500: '#3a9991',
					600: '#2e7a74',
					700: '#235b57',
					800: '#173c3a',
					900: '#0c1d1d',
				},
				accent: {
					50: '#f0f9ff',
					100: '#e0f2fe',
					200: '#b9e5fe',
					300: '#7cd1fd',
					400: '#36bafc',
					500: '#0da2e7',
					600: '#0182c5',
					700: '#02669f',
					800: '#065083',
					900: '#0b436d',
				},
				caspary: {
					'caspary-blue': '#2c5c6a',
					'caspary-blue-light': '#A9CFCF',
					'caspary-gray': '#2B2B2A',
					'caspary-gray-medium': '#B4B1B8',
					'caspary-light-gray': '#7B7B7B',
					'caspary-text': '#4A4A49',
					'caspary-purple': 'var(--color-purple)',
					'caspary-purple-dark': '#9D939D',
					'caspary-footer': '#5d4d5e',
				},
			},
			fontFamily: {
				'headline': ['apparat', 'Arial', 'sans-serif'],
				'body': ['Roboto Slab', 'Georgia', 'serif'],
				'light': ['apparat-light'],
				'light-body': ['Roboto Slab light'],
				'sans': ['apparat', 'ui-sans-serif', 'system-ui'],
				'serif': ['Roboto Serif', 'Georgia'],
				'mono': ['ui-monospace', 'SFMono-Regular'],
			},
			fontSize: {
				'xs': '.75rem',
				'sm': '.875rem',
				'base': '1rem',
				'lg': '1.125rem',
				'xl': '1.25rem',
				'2xl': '1.5rem',
				'3xl': '1.875rem',
				'4xl': '2.25rem',
				'5xl': '3rem',
				'6xl': '3.75rem',
				'7xl': '4.5rem',
			},
			spacing: {
				'18': '4.5rem',
				'88': '22rem',
				'128': '32rem',
			},
			borderRadius: {
				'sm': '0.125rem',
				'DEFAULT': '0.25rem',
				'md': '0.375rem',
				'lg': '0.5rem',
				'xl': '0.75rem',
				'2xl': '1rem',
				'3xl': '1.5rem',
			},
			container: {
				center: true,
				padding: {
					DEFAULT: '1rem',
					sm: '2rem',
					lg: '4rem',
					xl: '5rem',
					'2xl': '6rem',
				},
			},
			typography: (theme) => ({
				DEFAULT: {
					css: {
						color: theme('colors.caspary-text'),
						fontWeight: '300',
						strong: {
							color: theme('colors.caspary-gray'),
							fontWeight: '700',
						},
						em: {
							fontStyle: 'italic',
						},
						a: {
							color: theme('colors.caspary-purple'),
							textDecoration: 'underline',
							fontFamily: theme('fontFamily.serif'),
							fontStyle: 'italic',
							'&:hover': {
								color: theme('colors.caspary-purple-dark'),
							},
						},
						h2: {
							color: theme('colors.caspary-gray'),
							fontFamily: theme('fontFamily.headline'),
							fontWeight: '400',
							marginTop: '2rem',
							marginBottom: '1rem',
						},
						h3: {
							color: theme('colors.caspary-gray'),
							fontFamily: theme('fontFamily.headline'),
							fontWeight: '400',
							marginTop: '1.5rem',
							marginBottom: '0.75rem',
						},
						h4: {
							color: theme('colors.caspary-gray'),
							fontFamily: theme('fontFamily.headline'),
							fontWeight: '400',
							marginTop: '1rem',
							marginBottom: '0.5rem',
						},
						p: {
							marginBottom: '1rem',
							lineHeight: '1.75',
						},
						ul: {
							listStyleType: 'disc',
							paddingLeft: '1.5rem',
							marginBottom: '1rem',
							'li': {
								marginBottom: '0.25rem',
								paddingLeft: '0.25rem',
							},
						},
						ol: {
							listStyleType: 'decimal',
							paddingLeft: '1.5rem',
							marginBottom: '1rem',
							'li': {
								marginBottom: '0.25rem',
								paddingLeft: '0.25rem',
							},
						},
						'ul ul, ol ol': {
							marginTop: '0.5rem',
							marginBottom: '0.5rem',
						},
					},
				},
				lg: {
					css: {
						fontSize: '1.125rem',
						lineHeight: '1.75',
						p: {
							marginBottom: '1.25rem',
						},
					},
				},
			}),
		},
	},
	plugins: [
		require('@tailwindcss/typography'),
		require('@tailwindcss/aspect-ratio'),
	],
}
