# Include routes from Thorwarth.BaseSite
-
  name: 'Thorwarth.BaseSite'
  uriPattern: '<Thorwarth.BaseSiteSubroutes>'
  subRoutes:
    'Thorwarth.BaseSiteSubroutes':
      package: 'Thorwarth.BaseSite'
