-
  name: 'Caspary.Site Search API'
  uriPattern: 'api/search'
  defaults:
    '@package': 'Caspary.Site'
    '@controller': 'Search'
    '@action': 'search'
    '@format': 'json'
  httpMethods: ['GET']

-
  name: 'Caspary.Site'
  uriPattern: '<CasparySubroutes>'
  defaults:
    '@package': 'Caspary.Site'
  subRoutes:
    CasparySubroutes:
      package: 'Caspary.Site'