Neos:
  Neos:
    sites:
      '*':
        uriPathSuffix: ''
    nodeTypes:
      groups:
        caspary:
          label: 'Caspary Elements'
          position: 100
#     userInterface:
#       translation:
#         autoInclude:
#           'Caspary.Site': ['Main']